### ISSUE TITLE
10 User

### ISSUE THREAD

**Issue by MateLoncar** [MateLoncar/capstone-project#17]
Value proposition
As a user, 
I want to be required to input my username before accessing the map, 
so that I have a personalized experience and only see and delete the markers "I want to go there" I have created.

Description
The mapping application currently allows all users to access and view all markers, including those created by other users. To ensure privacy and provide a personalized experience, we want to add a feature that requires users to input their username before accessing the map. Users will only see and be able to delete markers "I want to go there" that they have created, and every marker "I was there" will display the name of the user who created it.

Acceptance criteria

- [ ] The user must input their username before accessing the map.
- [ ] The map should only display markers created by the current user.
- [ ] The user should be able to create new markers and save them to the map.
- [ ] Every marker should display the name of the user who created it.
- [ ] The user should only be able to delete markers that they have created.

Tasks

- [ ] Modify the code to require users to input their username before accessing the map.
- [ ] Update the database to associate each marker with a specific user.
- [ ] Modify the code to only display markers created by the current user.
- [ ] Add functionality to allow users to create and save new markers to the map.
- [ ] Modify the marker display code to show the name of the user who created each marker.
- [ ] Add functionality to allow users to delete only markers they have created.
- [ ] Update the UI to prominently display the user's username and markers.

Size: XL

**Comment by mbosselmann** [comment]
Hi Mate,
well done! I have one question: Why do you describe your app? It could be so much easier to understand what you want for the user with this user story if you use wireframes instead.

Also there is a contradicting part in your user story:
- You write: "Additionally, every marker will display the name of the user who created it, so that other users can see who has had that experience." But also "Users will only be able to see markers that they have created and will be able to delete only those markers." Which one is correct?

And I forgot to mention in my review of your user story number 8: the formatting of your checkboxes is not correct. I think there is a space missing betwenn `-` and `[ ]`. If you add the space it should solve the formatting issue.

**Comment by MateLoncar** [comment]
i hope i fixed it,thank you for your feedback :)

**Comment by CJAkkuec** [comment]
Hey there! As it stands (with regards to your API developer story) I'm fairly certain that this wouldn't be your tenth user story. 🤔 

Also,
> Users will only see and be able to delete markers that they have created, and every marker will display the name of the user who created it.

If the user is only ever going to see their own content, I'm not sure why the marker needs to bear their own name?

>  Update the database to associate each marker with a specific user.

I think you might benefit from a database with two separate collections, one for the users and one for the markers, seeing as how one user can put down many markers, but each marker is specific to one user.

**Comment by MateLoncar** [comment]
I wanted to tell that user will see markers where they want to go,another "experience" markers will be visible for everyone
